heroku apps:destroy --confirm  afternoon-everglades-2805
heroku apps:destroy --confirm  boiling-atoll-4826 
heroku apps:destroy --confirm  cryptic-harbor-1448
heroku apps:destroy --confirm  enigmatic-citadel-2097
heroku apps:destroy --confirm  enigmatic-thicket-9046 
heroku apps:destroy --confirm  fast-journey-1018 
heroku apps:destroy --confirm  fathomless-refuge-8143 
heroku apps:destroy --confirm  fierce-spire-7011 
heroku apps:destroy --confirm  guarded-headland-4435 
heroku apps:destroy --confirm  immense-springs-1556 
heroku apps:destroy --confirm  infinite-reef-6490 
heroku apps:destroy --confirm  lit-cove-4390 
heroku apps:destroy --confirm  mighty-brook-9124 
heroku apps:destroy --confirm  murmuring-coast-2881 
heroku apps:destroy --confirm  obscure-garden-2195 
heroku apps:destroy --confirm  peaceful-bastion-6126 
heroku apps:destroy --confirm  protected-everglades-7932 
heroku apps:destroy --confirm  serene-beyond-4102 
heroku apps:destroy --confirm  shrouded-basin-8357 
heroku apps:destroy --confirm  shrouded-plains-4659 
heroku apps:destroy --confirm  stark-journey-2306 
heroku apps:destroy --confirm  still-garden-6850 
heroku apps:destroy --confirm  thawing-mesa-9983

